import {brandDirectory} from '../src/brand-directory.js';
import {escapeHTML} from '../src/glossary-render.js';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {glossaryEntries} from '../src/glossary.js';
import {materials,journeys,networks,articles} from '../src/data.js';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{}),...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_URL||'http://127.0.0.1:4173/';
const results=[];await fs.mkdir('docs/screenshots',{recursive:true});
async function go(route){await page.goto(base+'#/'+route);await page.locator('h1').waitFor();assert.ok(!await page.getByText('A thread we couldn’t follow.',{exact:true}).count(),'Unexpected route failure: '+route);}
try{
 await go('atlas/wool');assert.equal(await page.locator('.fiber-option').count(),30);await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Center on this route'}).click();await page.getByRole('button',{name:'Map',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Map',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Globe',exact:true}).click();await page.getByRole('button',{name:'Dubbo Grower',exact:false}).click();assert.ok(await page.locator('.node-detail').count());await page.getByRole('button',{name:'Close place detail'}).click();await page.getByRole('button',{name:'Center on this route'}).click();await page.screenshot({path:'docs/screenshots/atlas-desktop.png',fullPage:true});results.push('Atlas: globe/map, zoom/reset and node details');
 await go('materials');await page.getByLabel('Search material library').fill('pashmina');assert.equal(await page.locator('.material-card h3').first().textContent(),'Cashmere');assert.ok(await page.getByRole('heading',{name:'Cashmere',exact:true}).count());await page.getByRole('button',{name:'Reset',exact:true}).click();await page.locator('#library-family').selectOption('Plant');await page.locator('#library-sort').selectOption('az');assert.ok(await page.locator('.material-card').count()>1);await page.getByRole('button',{name:'Save Abacá',exact:true}).click();await go('saved');assert.ok(await page.getByRole('heading',{name:'Abacá',exact:true}).count());await page.reload();assert.ok(await page.getByRole('heading',{name:'Abacá',exact:true}).count());results.push('Library: search aliases, filter, sort, save and reload persistence');
 await go('compare');await page.locator('#compare-0').selectOption('cashmere');await page.waitForURL(/cashmere/);assert.ok(await page.locator('table').getByText('Cashmere',{exact:true}).count());results.push('Comparison selects update URL and content');
 await go('science');await page.getByRole('button',{name:'2/2 twill',exact:true}).click();assert.equal(await page.getByRole('button',{name:'2/2 twill',exact:true}).getAttribute('aria-pressed'),'true');await page.locator('#denier').fill('0');assert.match(await page.locator('#diameter').textContent(),/valid/);await page.locator('#denier').fill('5');assert.match(await page.locator('#diameter').textContent(),/22.64/);await page.screenshot({path:'docs/screenshots/science-desktop.png',fullPage:true});results.push('Science: weave switching, invalid values and numeric output');
 await page.getByRole('button',{name:'Search the atlas'}).click();await page.getByRole('searchbox',{name:'Search all materials, glossary terms, journeys and field notes'}).fill('ECONYL');await page.locator('.search-result').first().click();await page.waitForURL(/fiber\/econyl/);assert.equal(await page.locator('dialog[open]').count(),0);results.push('Global search routes and closes its dialog');
 for(const m of (process.env.QUICK_TEST?[]:materials)){await go('fiber/'+m.id);assert.ok(await page.getByRole('heading',{name:m.name,exact:true}).count());}for(const j of (process.env.QUICK_TEST?[]:journeys)){await go('journey/'+j.id);}if(!process.env.QUICK_TEST)results.push(`All ${materials.length} material profiles and ${journeys.length} journey detail routes render`);
 for(const t of ['overview','history','science','journeys','care'])await go('fiber/wool/'+t);
 for(const path of ['atlas/wool','materials','brands','compare','journeys','regions','learn','science','history','glossary','sources','about','privacy']){
  await go(path);const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();const violations=a.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}));if(violations.length)results.push({accessibility:path,violations});
  for(const width of [1440,768,390]){await page.setViewportSize({width,height:900});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow)console.log('OVERFLOW',path,width,await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(x=>x.getBoundingClientRect().right>innerWidth+1).map(x=>({tag:x.tagName,class:x.className,right:x.getBoundingClientRect().right})).slice(0,15)));assert.equal(overflow,false,'Horizontal overflow: '+path+' @ '+width);}
 }
 results.push('All main sections checked at 1440, 768 and 390 pixels');
 await page.setViewportSize({width:390,height:844});await go('atlas/wool');await page.screenshot({path:'docs/screenshots/atlas-mobile.png',fullPage:true});await go('materials');await page.screenshot({path:'docs/screenshots/library-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await go('materials');await page.screenshot({path:'docs/screenshots/library-desktop.png',fullPage:true});
 await page.goto(base+'#/fiber/%3Cscript%3E');assert.ok(await page.getByRole('heading',{name:'A thread we couldn’t follow.'}).count());await page.goto(base+'#/materials?q=%3Cimg%20src=x%20onerror=alert(1)%3E');assert.equal(await page.locator('#main img').count(),0);results.push('Unknown routes and escaped search input handled');

 await context.setOffline(false);await go('glossary');await page.getByLabel('Search glossary',{exact:true}).fill('cottonisation');assert.match(await page.locator('#glossary-results details summary').first().textContent(),/^Cottonization/);await page.getByRole('button',{name:'Reset',exact:true}).click();await page.locator('#glossary-category').selectOption('Measurements');await page.getByRole('button',{name:'D',exact:true}).click();assert.match(await page.locator('#glossary-results details summary').first().textContent(),/^Denier/);await page.getByRole('button',{name:'Expand all',exact:true}).click();await page.getByRole('link',{name:'Read the full denier definition',exact:false}).click();await page.getByRole('heading',{name:'Denier',exact:true}).waitFor();assert.ok(await page.getByRole('heading',{name:'Sources & further reading',exact:true}).count());
 for(const t of glossaryEntries){await go('glossary/'+t.id);assert.equal(await page.locator('h1').textContent(),t.term);}
 await go('glossary/denier');assert.equal((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.length,0);await page.screenshot({path:'docs/screenshots/glossary-definition.png',fullPage:true});
 const plain=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const reader=await plain.newPage();
 for(const t of glossaryEntries){const response=await reader.goto(base+'glossary/'+t.id+'/');assert.equal(response.status(),200);assert.equal(await reader.locator('h1').textContent(),t.term);assert.ok((await reader.locator('main').textContent()).includes(t.explanation));assert.equal(await reader.locator('link[rel=canonical]').getAttribute('href'),'https://chasehendrick.github.io/FibersOfEarth/glossary/'+t.id+'/');const schema=JSON.parse(await reader.locator('script[type="application/ld+json"]').textContent());assert.equal(schema['@graph'][0].description,t.definition);}
 await reader.goto(base+'glossary/');assert.equal(await reader.locator('.glossary-static-list h2 a').count(),glossaryEntries.length);await reader.getByRole('link',{name:'Denier',exact:true}).click();await reader.getByRole('link',{name:'Micron',exact:true}).click();assert.equal(await reader.locator('h1').textContent(),'Micron');await reader.screenshot({path:'docs/screenshots/glossary-mobile.png',fullPage:true});assert.equal(await reader.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await plain.close();
 // Field notes must remain complete, navigable and accessible without JavaScript.
 const notesContext=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
 const notes=await notesContext.newPage();
 const localLinks=new Set();
 for(const a of articles){
  const response=await notes.goto(base+'learn/'+a.id+'/');assert.equal(response.status(),200,a.id);
  assert.equal(await notes.locator('h1').textContent(),a.title);
  const content=await notes.locator('main').textContent();
  for(const [heading,paragraph] of a.sections){assert.ok(content.includes(heading));assert.ok(content.includes(paragraph));}
  assert.equal(await notes.locator('link[rel=canonical]').getAttribute('href'),'https://chasehendrick.github.io/FibersOfEarth/learn/'+a.id+'/');
  const schema=JSON.parse(await notes.locator('script[type="application/ld+json"]').textContent());assert.equal(schema.headline,a.title);assert.equal(schema.citation.length,a.sources.length);
  for(const href of await notes.locator('a[href]').evaluateAll(els=>els.map(e=>e.href))){const link=new URL(href);if(link.origin===new URL(base).origin){link.hash='';localLinks.add(link.href);}}
  assert.equal(await notes.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,a.id+' mobile overflow');
 }
 for(const href of localLinks)assert.equal((await page.request.get(href)).status(),200,href);
 await notes.goto(base+'learn/');assert.equal(await notes.locator('.glossary-static-list h2 a').count(),articles.length);
 await notes.getByRole('link',{name:'Summer cloth: read beyond the fiber label.',exact:true}).click();
 await notes.getByRole('link',{name:'Fresco',exact:true}).click();assert.equal(await notes.locator('h1').textContent(),'Fresco');
 await notesContext.close();
 await go('article/summer-cloth');assert.ok(await page.locator('.term-link').count()>0);
 await page.getByRole('link',{name:'Reading edition',exact:false}).click();await page.waitForURL(/learn\/summer-cloth\//);
 assert.equal((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.length,0);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/screenshots/field-note-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 await page.goto(base+'learn/');assert.equal((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.length,0);
 results.push(`Field notes: ${articles.length} JavaScript-free guides, index, glossary and material links, citations, metadata, mobile layout and accessibility`);
 // Directory searches, saved brands and exports must work without a server dependency.
 await go('brands');assert.equal(await page.locator('.brand-card').count(),24);
 await page.getByRole('button',{name:'Next',exact:true}).click();assert.match(page.url(),/page=2/);
 await page.getByRole('searchbox',{name:'Search brands',exact:true}).fill('Ermenegildo Zegna');assert.equal(await page.locator('.brand-card').count(),1);
 await page.getByRole('button',{name:'Save brand ZEGNA',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Unsave brand ZEGNA',exact:true}).waitFor();
 await page.getByRole('button',{name:'Reset',exact:true}).click();await page.getByLabel('My saved brands on this device').check();assert.equal(await page.locator('.brand-card').count(),1);
 await page.getByRole('button',{name:'Compare saved brands',exact:true}).click();assert.ok((await page.locator('#brand-comparison').textContent()).includes('ZEGNA'));
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export saved brands',exact:true}).click();const download=await downloadPromise;const exported=JSON.parse(await fs.readFile(await download.path(),'utf8'));assert.deepEqual(exported.entries.map(b=>b.id),['zegna']);
 await page.getByRole('button',{name:'Reset',exact:true}).click();await page.locator('#brand-country').selectOption('Italy');await page.locator('#brand-depth').selectOption('catalog');assert.ok(await page.locator('.brand-card').count());
 await go('brands?page=NaN');assert.match(await page.locator('#brand-count').textContent(),/Page 1 of/);
 await go('brands?q=%3Cimg%20src=x%20onerror=alert(1)%3E');assert.equal(await page.locator('#brand-results img').count(),0);
 await go('brand/fox-brothers');assert.ok((await page.locator('main').textContent()).includes('1772'));assert.equal((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.length,0);
 await go('brands');await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:'docs/screenshots/brand-directory-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 const brandReaderContext=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const brandReader=await brandReaderContext.newPage();
 await brandReader.goto(base+'brands/');assert.equal(await brandReader.locator('.directory-index a').count(),brandDirectory.length);assert.equal(await brandReader.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 for(const b of [brandDirectory.find(b=>b.id==='fox-brothers'),brandDirectory.find(b=>b.id==='zegna'),brandDirectory.find(b=>b.depth==='catalog'),[...brandDirectory].sort((a,b)=>b.name.length-a.name.length)[0]]){await brandReader.goto(base+'brands/'+b.id+'/');assert.equal(await brandReader.locator('h1').textContent(),b.name);assert.equal(await brandReader.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,b.name);}
 await brandReaderContext.close();
 // Check every generated record and canonical path directly, then browser-test representative pages.
 for(const b of brandDirectory){const html=await fs.readFile('dist/brands/'+b.id+'/index.html','utf8');assert.ok(html.includes(`<h1>${escapeHTML(b.name)}</h1>`),b.id);assert.ok(html.includes('https://chasehendrick.github.io/FibersOfEarth/brands/'+b.id+'/'),b.id);assert.ok(html.includes('Open research questions'));}
 await page.goto(base+'brands/fox-brothers/');assert.equal((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.length,0);
 const exportedDirectory=await page.request.get(base+'brands/directory.json');assert.equal((await exportedDirectory.json()).entries.length,brandDirectory.length);
 results.push(`Brand directory: ${brandDirectory.length} generated pages audited; search, filters, pagination, saved-brand persistence, comparison, JSON exports, representative JavaScript-free pages, mobile layouts and accessibility passed`);

 const sitemap=await page.request.get(base+'sitemap.xml');assert.equal(sitemap.status(),200);assert.equal((await sitemap.text()).match(/<loc>/g).length,glossaryEntries.length+materials.length+articles.length+brandDirectory.length+5);assert.equal((await page.request.get(base+'glossary/missing/')).status(),404);
 await page.goto(base+'glossary/denier/');assert.equal((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.length,0);results.push(`Glossary: aliases, topic/letter filters, ${glossaryEntries.length} detail routes, ${glossaryEntries.length+1} JavaScript-free pages, related links, metadata, structured data, sitemap and accessibility`);
 await context.setOffline(false);await go('fiber/wool/science');assert.ok(await page.getByRole('heading',{name:'Structure & chemistry',exact:true}).count());assert.ok(await page.locator('.key-figures .fact-row').count()>=2);assert.ok(await page.locator('.term-link').count()>0);assert.ok((await page.locator('.cite-text').textContent()).includes('Fibers of Earth'));
 await go('materials');await page.getByLabel('Search material library').fill('cashmer');assert.equal(await page.locator('.material-card h3').first().textContent(),'Cashmere');await page.getByLabel('Search material library').fill('law:cites');assert.ok(await page.locator('.match-snippet mark').count()>0);
 await go('science');await page.locator('#count-value').fill('30');await page.locator('#count-unit').selectOption('ne');assert.match(await page.locator('#count-out').textContent(),/19\.68/);await page.locator('#weight-value').fill('1');await page.locator('#weight-unit').selectOption('oz');assert.match(await page.locator('#weight-out').textContent(),/33\.9/);
 await go('atlas/wool');assert.ok(await page.locator('.route.active .route-line').count()>0);assert.ok(await page.locator('.route-chevron').count()>0);assert.equal(await page.locator('[data-globe="spin"]').getAttribute('aria-pressed'),'false');await page.locator('[data-globe="spin"]').click();assert.equal(await page.locator('[data-globe="spin"]').getAttribute('aria-pressed'),'true');await page.locator('[data-globe="spin"]').click();
 await page.locator('[data-globe="spin"]').click().catch(()=>{});for(const id of Object.keys(networks)){const j=journeys.find(x=>x.fiber===id);await go('atlas/'+id);const shown=await page.locator('.map-node').evaluateAll(els=>els.map(e=>e.dataset.node));for(const k of new Set(j.keys))assert.ok(shown.includes(k),`${id}: stop ${k} not visible in home view`);}
 results.push('Every mapped fiber opens centered with all route stops visible');
 const readerM=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const rp=await readerM.newPage();
 for(const m of materials){const res=await rp.goto(base+'materials/'+m.id+'/');assert.equal(res.status(),200,m.id);assert.equal(await rp.locator('h1').textContent(),m.name);assert.equal(await rp.locator('link[rel=canonical]').getAttribute('href'),'https://chasehendrick.github.io/FibersOfEarth/materials/'+m.id+'/');const ld=JSON.parse(await rp.locator('script[type="application/ld+json"]').textContent());assert.equal(ld['@graph'][0].headline,m.name);assert.ok((await rp.locator('main').textContent()).includes(m.composition));}
 await rp.goto(base+'materials/');assert.equal(await rp.locator('.glossary-static-list h3 a').count(),materials.length);await Promise.all([rp.waitForURL(/materials\/wool\//),rp.getByRole('link',{name:'Merino wool',exact:true}).click()]);assert.equal(await rp.locator('h1').textContent(),'Merino wool');assert.equal(await rp.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 await readerM.close();await page.goto(base+'materials/cotton/');await page.locator('h1').waitFor();{const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(a.violations.map(v=>v.id),[]);}
 results.push(`Material reading edition: ${materials.length} JavaScript-free pages with canonical URLs, structured data, index and accessibility`);
 await go('atlas/linen');const gsvg=page.locator('.globe-svg');const gb=await gsvg.boundingBox();await page.mouse.move(gb.x+gb.width/2,gb.y+gb.height/2);const y0=await page.evaluate(()=>scrollY);const km0=await page.locator('.scale-bar text').textContent();for(let i=0;i<3;i++)await page.mouse.wheel(0,-120);await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>scrollY),y0);assert.notEqual(await page.locator('.scale-bar text').textContent(),km0);
 await gsvg.focus();await page.keyboard.press('ArrowLeft');await page.keyboard.press('-');assert.match(await page.locator('#globe-status').textContent(),/^Zoom [\d.]+ times, centered near/);await page.keyboard.press('0');
 assert.ok(await page.locator('[data-map-tool="fullscreen"]').count());
 await page.getByRole('button',{name:'Display settings'}).first().click();assert.equal((await new AxeBuilder({page}).include('#search-dialog').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.length,0);await page.getByLabel('Reduce motion',{exact:false}).check();await page.getByLabel('Underline links',{exact:false}).check();await page.keyboard.press('Escape');await page.reload();await page.locator('.globe-svg').waitFor();assert.match(await page.evaluate(()=>document.documentElement.className),/a11y-still.*a11y-underline|a11y-underline.*a11y-still/);await page.evaluate(()=>localStorage.removeItem('fibersOfEarth.display.v1'));await page.reload();
 await go('properties');await page.locator('[data-sort="density"]').click();const lightest=await page.locator('#prop-body tr th a').first().textContent();await page.locator('[data-sort="density"]').click();assert.notEqual(await page.locator('#prop-body tr th a').first().textContent(),lightest);assert.equal(await page.locator('th[aria-sort="descending"]').count(),1);
 results.push('Properties table sorts by column in both directions');
 results.push('Globe scroll zoom, keyboard control with live status, full screen control, and persistent display settings');
 results.push('Research layer: detail sections, key figures, glossary links, citations, ranked typo-tolerant search, converters, raised routes and spin control');
 await context.setOffline(true);await page.goto(new URL('../dist/offline.html',import.meta.url).href+'#/materials');await page.locator('h1').waitFor();assert.ok(await page.locator('.material-card').count()>0);results.push('Standalone HTML opens offline with populated library');await page.goto(new URL('../dist/offline.html',import.meta.url).href+'#/article/summer-cloth');await page.getByRole('heading',{name:'Summer cloth: read beyond the fiber label.',exact:true}).waitFor();assert.ok((await page.locator('.reading').textContent()).includes('running meter'));results.push('New field note reads offline with glossary links');
 await page.goto(new URL('../dist/offline.html',import.meta.url).href+'#/brands');await page.getByRole('searchbox',{name:'Search brands',exact:true}).fill('fox brothers');await page.locator('.brand-card h2 a').first().click();await page.getByRole('heading',{name:'Fox Brothers',exact:true,level:1}).waitFor();assert.ok((await page.locator('main').textContent()).includes('1772'));results.push('Brand directory search and research notes work fully offline');
 assert.deepEqual(errors,[]);results.push('No browser JavaScript errors');
 await fs.writeFile('docs/browser-results.json',JSON.stringify({date:new Date().toISOString().slice(0,10),browser:'Chromium',results},null,2));console.log(JSON.stringify(results,null,2));assert.equal(results.filter(x=>x.violations?.length).length,0,'Accessibility violations');
}catch(e){await page.screenshot({path:'docs/screenshots/failure.png',fullPage:true});console.error(e);console.log(JSON.stringify(results,null,2));process.exitCode=1;}finally{await browser.close();}
