const brandQuestions={"zegna": "Is this a ZEGNA garment, or a garment made by another house using Zegna cloth?", "brunello-cucinelli": "What are the exact composition, knit structure and care instructions for this item?", "john-smedley": "Is this cotton, merino or a blend, and what do its knit gauge and care label describe?", "johnstons-of-elgin": "Is this piece woven or knitted, and which fiber percentages and care instructions apply?", "vitale-barberis-canonico": "What is the exact VBC article number, and who made the finished garment?", "reda": "Which Reda range and article is specified, and does the garment label support its care claims?"};
const brandAliases={zegna:'Ermenegildo Zegna', 'vitale-barberis-canonico':'VBC', reda:'Reda 1865 Successori Reda'};
// Brand descriptions are attributed to their publishers. No affiliation or performance endorsement.
const rows=[
 ['tencel','TENCEL™','Branded fiber family','lyocell','Lenzing’s brand includes lyocell and modal products. Read the generic composition to identify which fiber is present.','The brand’s history follows the commercial development and branding of regenerated cellulose. Its portfolio spans more than one generic fiber type.','https://www.lenzing.com/technology-production/technologies/'],
 ['ecovero','LENZING™ ECOVERO™','Branded viscose','viscose','A Lenzing viscose brand with producer-specific sourcing and process claims. Those claims should be checked for the particular product.','The brand developed around differentiated viscose sourcing and production. Its range later incorporated products using REFIBRA technology.','https://www.lenzing.com/products/brands/lenzingtm-ecoverotm/'],
 ['refibra','REFIBRA™','Feedstock technology','lyocell','Lenzing technology that incorporates recovered cellulose inputs into selected fiber products. The actual recycled share depends on the product.','REFIBRA has been associated with TENCEL lyocell and was extended to ECOVERO viscose. It identifies a technology rather than a separate generic fiber.','https://www.lenzing.com/newsroom/news-events/lenzing-expands-refibratm-technology-to-lenzingtm-ecoverotm-setting-new-responsible-viscose-standards-for-textile-circularity/'],
 ['econyl','ECONYL®','Regenerated nylon brand','recycled-nylon','Aquafil’s regenerated nylon brand. Identify the product, composition and documented waste inputs rather than assuming all feedstock is fishing nets.','The brand connects nylon recovery with new yarn and product applications. It is a branded route within polyamide recycling, not a new natural fiber.','https://econyl.aquafil.com/'],
 ['repreve','REPREVE®','Recycled-material platform','recycled-polyester','UNIFI’s brand spans recycled polyester, nylon and related products. Waste streams and product specifications vary within the platform.','REPREVE expanded from recycled-fiber branding into multiple feedstock and product lines. FiberPrint and U-TRUST are associated traceability tools.','https://repreve.com/'],
 ['seaqual','SEAQUAL® YARN','Recycled-yarn program','recycled-polyester','A yarn program associated with recovered marine plastic. Check the exact composition and marine-derived share of the specified yarn.','SEAQUAL connects collection and polymer processing with yarn partners. The program name does not describe the entire composition of every finished fabric.','https://www.seaqual.org/seaqual-yarn/'],
 ['spinnova','SPINNOVA®','Fiber technology','paper-yarn','A proprietary fiber-forming technology and ingredient brand using cellulose-rich inputs. It is distinct from ordinary viscose processing.','Spinnova’s development centers on turning a cellulose suspension into textile fiber. Commercial status and manufacturing capacity should be checked with the producer.','https://spinnova.com/fibre/'],
 ['infinna','Infinna™','Regenerated fiber brand','viscose','Infinited Fiber Company’s branded cellulose fiber made using its proprietary technology and textile-waste inputs.','Infinna developed as part of efforts to return cellulose-rich textile waste to fiber production. Pilot work, planned capacity and actual commercial supply are different milestones.','https://infinitedfiber.com/'],
 ['circulose','CIRCULOSE®','Recycled dissolving pulp','viscose','A recycled-cellulose pulp feedstock used by downstream fiber producers. It is not, by itself, the finished fiber name on a garment.','CIRCULOSE belongs to the development of textile-to-textile cellulose feedstocks. Its path continues through a separate fiber-making process before yarn and fabric.','https://circulose.com/'],
 ['naia','Naia™','Cellulose-acetate brand','acetate','Eastman’s cellulose-acetate textile brand. Product variants and recycled-content offerings should be distinguished.','Naia builds on cellulose-acetate chemistry with a contemporary branded textile range. A brand-level claim should be checked against the exact yarn or staple product.','https://naia.eastman.com/'],
 ['sorona','Sorona®','Partly bio-based polymer','polyester','A branded PTT polymer platform using a partly bio-based input route. It is not elastane and is not simply PET polyester under another name.','Sorona connects industrial biotechnology with polyester-family performance materials. Its brand programs cover particular apparel and carpet applications.','https://sorona.com/'],
 ['bemberg','Bemberg™','Cupro brand','cupro','Asahi Kasei’s cupro fiber brand, associated with regenerated cellulose from cotton linters.','Bemberg belongs to the history of cuprammonium cellulose and fine lining materials. The brand name identifies a producer’s product, while cupro names the fiber type.','https://www.asahi-kasei.com/fibers/en/bemberg/'],
 ['lycra','LYCRA®','Stretch-fiber brand','spandex','A familiar branded elastane offering within a wider technology portfolio. The word is often used loosely, so read the generic composition.','LYCRA became closely associated with stretch clothing. Its brand history follows the expansion of elastane into everyday apparel and technical fabric systems.','https://www.lycra.com/'],
 ['kevlar','Kevlar®','Para-aramid brand','para-aramid','A para-aramid product family used in engineered textile and composite applications. Whole-product testing determines protection.','Kevlar grew from high-performance polymer research at DuPont. The official brand destination now identifies Arclin; the generic fiber remains para-aramid.','https://www.arclin.com/kevlar/'],
 ['nomex','Nomex®','Meta-aramid brand','meta-aramid','A brand associated with heat-resistant meta-aramid materials and related product forms.','Nomex’s history connects polymer science with thermal-protection systems. Its official brand destination now identifies Arclin; fabric and garment specifications remain essential.','https://www.arclin.com/nomex/'],
 ['dyneema','Dyneema®','UHMWPE brand','polyethylene','A high-performance polyethylene product family. Fiber, fabric, laminate and rope constructions have different properties.','Dyneema developed around engineered polyethylene strength. Its textile applications extend from lightweight equipment to demanding technical systems.','https://www.dyneema.com/'],
 ['nuyarn','Nuyarn®','Yarn construction technology','wool','A proprietary yarn technology commonly associated with wool blends. It changes yarn construction rather than naming a new animal fiber.','Nuyarn’s story concerns how fibers are assembled into yarn. Evaluate the complete blend and tested fabric rather than transferring every brand claim to every garment.','https://nuyarn.com/'],
 ['zq','ZQ','Wool sourcing program','wool','A wool sourcing and assurance program, not a distinct species or generic fiber. Verify the applicable program scope for the product.','ZQ reflects the development of differentiated wool sourcing and grower relationships. Its name belongs in the provenance conversation alongside the underlying wool specification.','https://www.discoverzq.com/'],
 ['seacell','SeaCell™','Cellulose composite fiber','lyocell','A branded cellulose fiber incorporating seaweed material. It should not be described as a fabric made entirely from seaweed.','SeaCell is part of the development of functionalized cellulose fibers. Product formulation and evidence matter more than transferring general seaweed benefits to a textile.','https://smartfiber.de/en/seacell/'],
 ['coolmax','COOLMAX®','Performance-fiber technology','polyester','A performance brand associated with moisture-management fiber and fabric technologies. Exact polymer and recycled-content variants should be checked.','COOLMAX helped make engineered moisture management a familiar apparel claim. The actual effect depends on fiber geometry, yarn, fabric and garment design.','https://www.coolmax.com/'],
 ['wolf-vs-goat','Wolf vs Goat','Fabric-first apparel brand','wool','An apparel brand that publishes material education about merino micron, mill yarns and cloth construction. It is a reference brand for learning materials language, not a proprietary fiber.','Wolf vs Goat grew as a garment maker that names mill yarns and fiber grades in public product stories. Use those stories to practice separating mill yarn brands from fiber classes; they are attributed examples, not endorsements or proof of every batch.','https://www.wolfvsgoat.com/'],
 ['canali','Canali','Italian menswear house','wool','An Italian menswear house with roots in Triuggio, Brianza. Read its tailored garments through their fiber content, cloth construction and product documentation. The house name is not a proprietary fiber.','Canali dates its company foundation to 1934, following an earlier family tailoring workshop. Garment-house history does not establish a farm origin or an exclusive mill relationship.','https://anthology.canali.com/en/family/the-canali-family/'],
 ['loro-piana','Loro Piana','Textile maison (Quarona)','cashmere','A textile maison founded in Quarona known for fine wool and cashmere cloths and for producer-named weather finishes such as Storm System on documented products. It is a reference brand for mill provenance language, not a fiber class.','Loro Piana’s story combines spinning and weaving know-how in Piedmont with branded cloth collections. Fiber still comes from farms and herds (for example merino wool or cashmere goats); the maison name is finishing, design and commerce. Storm System and similar finish names should be read only where the producer documents them for a specific cloth.','https://www.loropiana.com/'],
 ['piacenza-1733','Piacenza 1733','Historic Biella mill house','wool','A historic Biella-area wool mill house (Fratelli Piacenza), publicly dating its founding to 1733 in Pollone. It is a reference entry for mill-house provenance, not a generic fiber.','Piacenza 1733 presents itself as a multi-century family wool mill in the Biella district. The educational point is longevity and place: a mill house can finish wool grown far from Piedmont. Do not invent supplier links from the atlas map; read producer pages for current collections and claims.','https://www.piacenza1733.com/'],
 ['paul-smith','Paul Smith','Designer menswear house','wool','A British designer house known for tailored menswear and cloth storytelling. It is a reference brand for reading designer-and-mill language, not a proprietary fiber.','Paul Smith’s public identity mixes British tailored clothing with cloth and mill references in product storytelling. Use the name to practice separating a designer house from the generic fiber and mill cloth on a hangtag; do not treat the house name as a fiber class or exclusive mill claim.','https://www.paulsmith.com/'],
 ['yves-salomon','Yves Salomon','Outerwear house','cashmere','A French house associated with fur, shearling and fine outerwear, including cashmere pieces. It is a reference brand for specialty outerwear materials language, not a proprietary fiber.','Yves Salomon’s public story centers on furrier craft and luxury outerwear constructions. Use it to separate house name, animal-fiber classes (for example cashmere or shearling) and finishing; verify current product composition on producer pages. Inclusion teaches materials vocabulary and is not an endorsement of fur.','https://www.yves-salomon.com/'],
 ["zegna","ZEGNA","Textile and menswear house","wool","ZEGNA is a menswear brand connected to a textile manufacturing group. Its history begins with a wool mill in Trivero. A Zegna cloth reference and a ZEGNA finished garment describe different products, even when they share a commercial name.","The group dates its foundation in Trivero to 1910. Its history describes a progression from wool-textile manufacture to a broader apparel and manufacturing business. The mill, garment brand and corporate group should remain distinct when interpreting product descriptions.","https://www.zegnagroup.com/en/overview/"],
 ["brunello-cucinelli","Brunello Cucinelli","Cashmere and apparel house","cashmere","Brunello Cucinelli is an apparel house closely associated with cashmere and Solomeo. The name identifies a designer and business, not a species, cashmere grade or universal fiber recipe. A collection can include many materials; the composition of each garment remains the starting point.","The company connects its beginnings in 1978 with colored cashmere knitwear. Its founder’s account describes experimenting with dyed women’s sweaters before expanding the business. That history concerns product design and commerce, rather than the discovery of cashmere as a fiber.","https://www.brunellocucinelli.com/en/company/cashmere.html"],
 ["john-smedley","John Smedley","British knitwear maker","wool","John Smedley is a knitwear maker associated with Lea Mills in Derbyshire. Its producer material descriptions distinguish extra-fine merino and the house’s Sea Island Cotton range. These are separate fiber stories; the maker’s name alone does not identify the composition of a particular sweater.","The producer history traces Lea Mills to 1784, initially making muslin and spinning cotton. The later knitwear story is a change in manufacturing activity. An old mill date should therefore be read as industrial heritage, not proof that every present product has been made unchanged since that year.","https://beta.johnsmedley.com/uk/discover/company-history/"],
 ["johnstons-of-elgin","Johnstons of Elgin","Scottish weaving and knitwear house","cashmere","Johnstons of Elgin is a Scottish textile house with weaving and knitwear traditions. Its history distinguishes the Elgin weaving mill and the Hawick knitting operation. Scottish manufacture describes a processing location; it does not establish that cashmere goats or wool-producing sheep were raised in Scotland.","The house traces its history to 1797. Its timeline dates the Hawick mill to 1980 and describes that development as a move into knitwear manufacturing. Keeping those dates separate explains why one company name can cover both woven and knitted textile traditions.","https://discover.johnstonsofelgin.com/227years/chapter-1"],
 ["vitale-barberis-canonico","Vitale Barberis Canonico","Italian cloth mill","wool","Vitale Barberis Canonico, often shortened to VBC, is a cloth mill associated with Pratrivero. A fabric carrying its name may be made into a garment by an unrelated tailor or apparel house. The cloth reference is therefore distinct from the identity of the finished garment maker.","The mill’s chronology cites a 1663 document for family textile activity and dates the named Vitale Barberis Canonico company to 1936. It also records a complete-cycle factory in Pratrivero in 1910. These are different milestones, not interchangeable claims about the age of one unchanged legal entity.","https://vitalebarberiscanonico.com/who-we-are/our-history/"],
 ["reda","Reda","Italian wool cloth mill","wool","Reda is a wool-textile mill associated with the Biella area. Its range includes cloth collections with distinct names and specifications. Reda, Reda Active and Reda Flexo should be read as company or product-range identities, not as interchangeable generic names for a single fiber.","The Biella archive network dates the wool mill founded by Carlo Reda in Valle Mosso to 1865. Reda’s own heritage account describes later manufacturing developments and acquisitions. The year in its branding is a heritage reference, not a fabric weight, wool grade or current production volume.","https://www.reda1865.com/us/heritage"]
];
export const brands=Object.fromEntries(rows.map(([id,name,type,base,composition,history,url])=>[id,{id,name,type,base,composition,history,aliases:brandAliases[id]||'',family:'Brands & technologies',tagline:type+' · understand the name behind the label.',feel:'Depends on the specified fiber grade, yarn and fabric construction.',uses:'See the linked underlying material and the producer’s product-specific documentation.',care:'Follow the finished product’s care label. A trademark does not specify the care needs of every blend or construction.',tradeoff:'Producer claims apply to defined products and comparisons. This atlas does not independently certify performance, sourcing or environmental claims.',question:brandQuestions[id]||'Which exact grade, composition and current producer documentation apply to this product?',sources:['brand-'+id],referenceOnly:true,brand:true,url}]));
export const brandSources=rows.map(([id,name,type,base,composition,history,url])=>({id:'brand-'+id,name:name.replace(/[™®]/g,''),title:'Official product information',url,note:'Producer source for brand identity and claimed technology. Inclusion is not an endorsement.'}));
